# Generated by Django 4.0.4 on 2022-06-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('up', 'upvote'), ('down', 'downvote')], default='up', max_length=4),
        ),
    ]
