# Generated by Django 4.0.4 on 2022-06-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_vote_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
