# Generated by Django 4.0.4 on 2022-06-08 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_alter_servertag_name'),
        ('posts', '0010_post_votes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servers.servertag'),
        ),
    ]
