# Generated by Django 4.0.4 on 2022-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='is_saved',
            field=models.BooleanField(default=True),
        ),
    ]
