# Generated by Django 4.0.4 on 2022-09-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='save',
            name='value',
            field=models.CharField(choices=[('save', 'save'), ('unsave', 'unsave')], default='save', max_length=8),
        ),
        migrations.AlterField(
            model_name='save',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='save',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_saves', to='posts.post'),
        ),
    ]
