# Generated by Django 4.0.4 on 2022-09-23 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0018_save_updated_save_value_alter_save_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='save',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
