# Generated by Django 4.0.4 on 2022-09-29 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_post_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='save',
        ),
        migrations.AddField(
            model_name='post',
            name='save',
            field=models.ManyToManyField(blank=True, null=True, related_name='saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
