# Generated by Django 4.0.4 on 2022-09-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_remove_post_save_post_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='save',
        ),
    ]
