# Generated by Django 4.0.4 on 2022-10-02 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0045_alter_server_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0022_post_save'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Save',
            new_name='PostSave',
        ),
        migrations.RemoveField(
            model_name='post',
            name='save',
        ),
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.ManyToManyField(blank=True, null=True, related_name='saves', to='servers.server'),
        ),
    ]
