# Generated by Django 4.0.4 on 2022-09-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0045_alter_server_image'),
        ('posts', '0022_post_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='save',
            field=models.ManyToManyField(blank=True, null=True, related_name='saves', to='servers.server'),
        ),
    ]
