# Generated by Django 4.0.4 on 2022-10-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_rename_save_postsave_remove_post_save_post_saved'),
        ('posts', '0024_remove_post_save_post_save'),
    ]

    operations = [
    ]
