# Generated by Django 4.0.4 on 2022-10-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_merge_20221002_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='saved',
            new_name='save',
        ),
    ]
