# Generated by Django 4.0.4 on 2022-10-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_rename_saved_post_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='save',
            new_name='saved',
        ),
    ]
