# Generated by Django 4.0.4 on 2022-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_vote_updated_alter_vote_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('up', 'upvote'), ('down', 'downvote')], max_length=4),
        ),
    ]
