# Generated by Django 4.0.4 on 2022-11-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0045_alter_server_image'),
        ('posts', '0031_post_downvotes_post_upvotes_alter_post_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='servers.serverposttag'),
        ),
    ]
