# Generated by Django 4.0.4 on 2022-11-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_post_updated_alter_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
