# Generated by Django 4.0.4 on 2022-11-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_reportpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='reason',
            field=models.CharField(choices=[('sr', 'server_rule'), ('c', 'copy_right'), ('hr', 'harassment'), ('mi', 'misinformation'), ('sh', 'self_harm'), ('spi', 'sharing_personal_info')], default='sr', max_length=3),
        ),
    ]
