# Generated by Django 4.0.4 on 2022-12-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_post_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dates',
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
