# Generated by Django 4.0.4 on 2022-12-14 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_remove_post_dates_alter_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dates',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
