# Generated by Django 4.0.4 on 2022-06-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.FloatField(default=0),
        ),
    ]
