# Generated by Django 4.0.4 on 2022-05-24 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvote',
        ),
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.ManyToManyField(related_name='downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote',
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.ManyToManyField(related_name='upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
