# Generated by Django 4.0.4 on 2022-06-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_downvotes_post_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
    ]
