# Generated by Django 4.0.4 on 2022-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_votes_alter_vote_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes_count',
            field=models.IntegerField(default=0),
        ),
    ]
