# Generated by Django 4.0.4 on 2022-07-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_save_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='is_saved',
        ),
    ]
