# Generated by Django 4.0.4 on 2022-06-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
