# Generated by Django 4.0.4 on 2022-06-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_servertags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerTags',
            new_name='ServerTag',
        ),
    ]
