# Generated by Django 4.0.4 on 2022-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_server_server_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='nsfw',
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(max_length=50),
        ),
    ]
