# Generated by Django 4.0.4 on 2022-07-27 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0011_alter_server_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_servers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('pub', 'عمومی'), ('pri', 'شخصی')], default='pri', max_length=3),
        ),
    ]
