# Generated by Django 4.0.4 on 2022-08-08 12:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0015_alter_server_header_image_alter_server_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servertag',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#A50277', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='servertag',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#FFB8EB', image_field=None, max_length=18, samples=None),
        ),
    ]
