# Generated by Django 4.0.4 on 2022-08-11 09:37

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0017_rename_servertag_serverposttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverposttag',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='servers.server'),
        ),
        migrations.CreateModel(
            name='ServerUserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('primary_color', colorfield.fields.ColorField(default='#A50277', image_field=None, max_length=18, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#FFB8EB', image_field=None, max_length=18, samples=None)),
                ('is_allowed', models.BooleanField(default=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='servers.server')),
            ],
        ),
    ]
