# Generated by Django 4.0.4 on 2022-08-11 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0018_alter_serverposttag_server_serverusertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverusertag',
            name='user',
            field=models.ManyToManyField(related_name='user_tag', to=settings.AUTH_USER_MODEL),
        ),
    ]
