# Generated by Django 4.0.4 on 2022-08-18 16:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0024_moderator_server_moderators'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moderator',
            new_name='ServerModerator',
        ),
    ]
