# Generated by Django 4.0.4 on 2022-08-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0025_rename_moderator_servermoderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='moderators',
        ),
        migrations.AddField(
            model_name='servermoderator',
            name='server',
            field=models.ManyToManyField(related_name='moderators', to='servers.server'),
        ),
    ]
