# Generated by Django 4.0.4 on 2022-08-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0026_remove_server_moderators_servermoderator_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servermoderator',
            name='server',
        ),
        migrations.AddField(
            model_name='server',
            name='moderators',
            field=models.ManyToManyField(related_name='moderators', to='servers.servermoderator'),
        ),
    ]
