# Generated by Django 4.0.4 on 2022-08-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0029_alter_servermoderator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servermoderator',
            name='server',
        ),
        migrations.AddField(
            model_name='server',
            name='moderators',
            field=models.ManyToManyField(related_name='server', to='servers.servermoderator'),
        ),
    ]
