# Generated by Django 4.0.4 on 2022-08-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0030_remove_servermoderator_server_server_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='moderators',
            field=models.ManyToManyField(blank=True, null=True, related_name='server', to='servers.servermoderator'),
        ),
    ]
