# Generated by Django 4.0.4 on 2022-08-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0031_alter_server_moderators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='moderators',
        ),
        migrations.AddField(
            model_name='servermoderator',
            name='server',
            field=models.ManyToManyField(blank=True, null=True, related_name='moderator_of', to='servers.servermoderator'),
        ),
    ]
