# Generated by Django 4.0.4 on 2022-08-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0032_remove_server_moderators_servermoderator_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermoderator',
            name='server',
            field=models.ManyToManyField(blank=True, null=True, related_name='moderator_of', to='servers.server'),
        ),
    ]
