# Generated by Django 4.0.4 on 2022-08-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0033_alter_servermoderator_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servermoderator',
            name='server',
        ),
    ]
