# Generated by Django 4.0.4 on 2022-08-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0036_alter_servermoderator_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servermoderator',
            name='allow_create_rule',
        ),
        migrations.RemoveField(
            model_name='servermoderator',
            name='allow_create_tag',
        ),
        migrations.RemoveField(
            model_name='servermoderator',
            name='allow_delete_post',
        ),
        migrations.RemoveField(
            model_name='servermoderator',
            name='allow_remove_moderator',
        ),
        migrations.RemoveField(
            model_name='servermoderator',
            name='allow_remove_user',
        ),
        migrations.CreateModel(
            name='ServerModeratorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_create_tag', models.BooleanField(default=True)),
                ('allow_create_rule', models.BooleanField(default=False)),
                ('allow_remove_user', models.BooleanField(default=True)),
                ('allow_remove_moderator', models.BooleanField(default=False)),
                ('allow_delete_post', models.BooleanField(default=False)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='servers.servermoderator')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='servers.server')),
            ],
        ),
    ]
