# Generated by Django 4.0.4 on 2022-08-24 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0038_remove_servermoderatorpermission_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermoderatorpermission',
            name='server',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='servers.server'),
        ),
    ]
