# Generated by Django 4.0.4 on 2022-08-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0039_servermoderatorpermission_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermoderatorpermission',
            name='allow_delete_tag',
            field=models.BooleanField(default=False),
        ),
    ]
