# Generated by Django 4.0.4 on 2022-08-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0040_servermoderatorpermission_allow_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermoderatorpermission',
            name='allow_delete_rule',
            field=models.BooleanField(default=False),
        ),
    ]
