# Generated by Django 4.0.4 on 2022-08-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0043_servermoderatorpermission_allow_add_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='image',
            field=models.ImageField(default='./static/images/reddit.jpg', upload_to='servers/pic/'),
        ),
    ]
