# Generated by Django 4.0.4 on 2022-12-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0046_serverfollow_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermoderatorpermission',
            name='allow_delete_report',
            field=models.BooleanField(default=True),
        ),
    ]
