# Generated by Django 4.0.4 on 2023-01-15 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0047_servermoderatorpermission_allow_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerUserLimitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('1', '۱ روز'), ('2', '۲ روز'), ('7', '۷ روز'), ('14', '۱۴ روز'), ('30', '۳۰ روز'), ('permanent', 'برای همیشه')], default='1', max_length=9)),
                ('info', models.TextField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limited_users', to='servers.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limited_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
