# Generated by Django 4.0.4 on 2023-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0048_serveruserlimitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveruserlimitation',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
