# Generated by Django 4.0.4 on 2023-02-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0049_alter_serveruserlimitation_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveruserlimitation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
