# Generated by Django 4.0.4 on 2022-07-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_profile_pic_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='./static/user/img/default.jpeg', null=True, upload_to='users/pic/'),
        ),
    ]
