# Generated by Django 4.0.4 on 2022-07-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://github.com/navid-az/reddit-clone/blob/main/reddit/user/static/user/img/default.jpeg', null=True, upload_to='users/pic/'),
        ),
    ]
