# Generated by Django 4.0.4 on 2022-07-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='./static/user/img/default.jpg', upload_to='users/pic/'),
        ),
    ]
