# Generated by Django 4.0.4 on 2022-08-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0018_alter_serverposttag_server_serverusertag'),
        ('user', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.ManyToManyField(to='servers.serverusertag'),
        ),
    ]
