# Generated by Django 4.0.4 on 2022-08-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0018_alter_serverposttag_server_serverusertag'),
        ('user', '0013_profile_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tag',
            field=models.ManyToManyField(related_name='user_tag', to='servers.serverusertag'),
        ),
    ]
