# Generated by Django 4.0.4 on 2022-08-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_profile_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tag',
        ),
    ]
