# Generated by Django 4.0.4 on 2022-08-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0021_alter_serverrule_creator'),
        ('user', '0015_remove_profile_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servers.serverusertag'),
        ),
    ]
