# Generated by Django 4.0.4 on 2022-08-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0021_alter_serverrule_creator'),
        ('user', '0016_profile_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tag',
        ),
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.ManyToManyField(default=1, to='servers.serverusertag'),
        ),
    ]
