# Generated by Django 4.0.4 on 2022-08-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0041_servermoderatorpermission_allow_delete_rule'),
        ('user', '0017_remove_profile_tag_profile_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='servers.serverusertag'),
        ),
    ]
