# Generated by Django 4.0.4 on 2022-11-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_profile_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=models.ImageField(blank=True, default='default/reddit.jpg', null=True, upload_to='users/header-pic/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default/reddit.jpg', null=True, upload_to='users/pic/'),
        ),
    ]
