# Generated by Django 4.0.4 on 2022-06-02 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(default='kir')),
                ('tag', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='server')),
                ('description', models.TextField(default='hello')),
                ('image', models.ImageField(upload_to='servers/pic/')),
                ('header_image', models.ImageField(upload_to='servers/header-pic/')),
                ('nsfw', models.BooleanField()),
                ('members_count', models.IntegerField(default=0)),
                ('online_count', models.IntegerField(default=0)),
                ('required_karma', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='servers.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_server', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
