# Generated by Django 4.0.4 on 2022-06-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='tag',
            field=models.CharField(default='nigg', max_length=50),
        ),
    ]
