# Generated by Django 4.0.4 on 2022-06-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
