# Generated by Django 4.0.4 on 2022-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_rename_servertags_servertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servertag',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
