# Generated by Django 4.0.4 on 2022-06-02 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0003_server_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='tag',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ServerFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='servers.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_servers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
