# Generated by Django 4.0.4 on 2022-07-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_alter_server_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.BooleanField(default=True),
        ),
    ]
