# Generated by Django 4.0.4 on 2022-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_alter_server_server_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='description',
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('pri', 'عمومی'), ('pub', 'شخصی')], default='pri', max_length=3),
        ),
    ]
