# Generated by Django 4.0.4 on 2022-07-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_remove_server_description_alter_server_server_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
