# Generated by Django 4.0.4 on 2022-07-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0013_alter_server_created_alter_serverfollow_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrule',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='servers.server'),
        ),
    ]
