# Generated by Django 4.0.4 on 2022-07-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0014_alter_serverrule_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='header_image',
            field=models.ImageField(default='https://play-lh.googleusercontent.com/nlptFyxNsb8J0g8ZLux6016kunduV4jCxIrOJ7EEy-IobSN1RCDXAJ6DTGP81z7rr5Zq', upload_to='servers/header-pic/'),
        ),
        migrations.AlterField(
            model_name='server',
            name='image',
            field=models.ImageField(default='https://play-lh.googleusercontent.com/nlptFyxNsb8J0g8ZLux6016kunduV4jCxIrOJ7EEy-IobSN1RCDXAJ6DTGP81z7rr5Zq', upload_to='servers/pic/'),
        ),
    ]
